In [8]:
import numpy as np
import random

def generiraj_vektor_nakljucno(stevilo_vzorcev):
    vektor = np.array([])

    for n in range(stevilo_vzorcev):
        vektor = np.append(vektor, random.uniform(0, 1))

    return(vektor)

In [9]:
def beri_zvok_mono(pot_do_datoteke):
    from scipy.io import wavfile
    Fs, y = wavfile.read(pot_do_datoteke)

    if(y.ndim == 1):
        vektor = y
    else:
        #zdruzi
        vektor = np.mean(y, axis=1)
        
    return normaliziraj(vektor)

In [10]:
def beri_zvok_stereo(pot_do_datoteke):
    from scipy.io import wavfile
    Fs, y = wavfile.read(pot_do_datoteke)

    if(y.ndim == 1):
        vektor = y
        vektor = np.append(vektor, vektor)
        vektor = np.reshape(vektor,(2, -1))
    else: 
        vektor = y
        vektor = np.reshape(vektor,(2, -1))

    return normaliziraj(vektor)

In [11]:
def normaliziraj(vektor):
    oblika = vektor.shape
    tmp = np.reshape(vektor, (-1, 1))
    maxNorm = abs(tmp[0])
    for n in tmp:
        if(abs(n) > maxNorm):
            maxNorm = abs(n)

    i = 0
    while i < tmp.size:
        tmp[i] = tmp[i] / maxNorm
        i += 1

    tmp = np.reshape(tmp, (oblika))
    
    return tmp

In [12]:
def normaliziraj_vektorsko(vektor):
    return vektor / np.linalg.norm(vektor)

In [13]:
import timeit

def testiraj_cas_izvajanja(vektor):
    start = timeit.default_timer()
    normaliziraj(vektor)
    cas = timeit.default_timer() - start

    start2 = timeit.default_timer()
    normaliziraj_vektorsko(vektor)
    cas2 = timeit.default_timer() - start2
    return np.array([[cas, cas2]])

In [14]:
if __name__ == '__main__':
    print(testiraj_cas_izvajanja(generiraj_vektor_nakljucno(1000000)))

[21693]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0.99999258]
[[0.228014  0.0002603]]
